### ISSUE TITLE
[FEATURE] Rename schedule app

### ISSUE THREAD

**Issue by NicKravchenko** [SoftwyRD/university-api#10]
To increase readability of whole project its better to change name of an app and every appearence of name "Schedule". It should be "Selection" instead.

It appears in:
#7 
#9 
App itself

**Comment by NicKravchenko** [comment]
@OmarNunezG  Please check it when you can

**Comment by OmarNunezG** [comment]
Hi, @NicKravchenko. Thanks for reaching out.

This is valid. We'll be working on it.
