### ISSUE TITLE
[FEATURE] Standardize functions return types

### ISSUE THREAD

**Issue by NicKravchenko** [SoftwyRD/university-api#13]
The code should not have defined functions return tupes for sake of standrtization.

**Comment by OmarNunezG** [comment]
Ok, working on it

**Comment by OmarNunezG** [comment]
Hi @NicKravchenko

Is there any reason you think this should be made?

Remember return types help others to know hot to use a function/method.

**Comment by NicKravchenko** [comment]
> Hi @NicKravchenko
> 
> Is there any reason you think this should be made?
> 
> Remember return types help others to know hot to use a function/method.

Its just my preference, both options are valid. But we need to follow the same pattern for all functions.

**Comment by OmarNunezG** [comment]
Specifying a function parameters and return types ["are generally a good thing for code clarity. You can immediately see what types of parameters or return type a particular function/method is accepting or returning"](https://stackoverflow.com/a/55664763).
