### ISSUE TITLE
[FEATURE] Add read only fields to serializers

### ISSUE THREAD

**Issue by NicKravchenko** [SoftwyRD/university-api#14]
Some serializers don't have read only fields specified, it would be good to add them.

**Comment by OmarNunezG** [comment]
Hi, thanks for reaching out.

Yes, we'll be working on it. Thanks!

**Comment by OmarNunezG** [comment]
Hi, @NicKravchenko

You mean the models' id field should be marked as read-only? Or is there any other field we should add?

**Comment by NicKravchenko** [comment]
> Hi, @NicKravchenko
> 
> You mean the models' id field should be marked as read-only? Or is there any other field we should add?

Every ID should be a read only, but also we need to limit as read only field those fields, which cant be changed, like:

- Foreign key of a user in selection.
- Created date in selection model.

Also created date should have "editable = False" in model definition.

**Comment by OmarNunezG** [comment]
Perfect!
