### ISSUE TITLE
[BUG]  Subject creation doesnt have subject ID

### ISSUE THREAD

**Issue by NicKravchenko** [SoftwyRD/university-api#33]
# Description
Serializer does not require for a user subject ID, so it cant be created properly.

## Problem
Subjects cant be created

## Solution
Add extra_kwargs for subject serializer which will have "subject": {"write_only": True}

**Comment by NicKravchenko** [comment]
@OmarNunezG hope you fix it asap

**Comment by OmarNunezG** [comment]
Fixed on a3e93f3.
